# Generated by Django 4.2.3 on 2023-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviemodel",
            options={
                "verbose_name": "MovieModel",
                "verbose_name_plural": "MovieModels",
            },
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
